# Generated by Django 4.2.5 on 2024-01-07 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0004_alter_item_item_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="item_image",
            field=models.CharField(
                default="https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Pizza-3007395.jpg/1280px-Pizza-3007395.jpg",
                max_length=500,
            ),
        ),
    ]
